core/urls.py
from django.urls import path
from .views import fornecedores, IndexView, produto, produtos, representante, fornecedor, representantes, \
    UpadteProdutoView, DeleteProdutoView, UpadteRepresentanteView, \
    DeleteRepresentanteView, UpadteFornecedorView, DeleteFornecedorView


app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('produto/', produto, name='produto'),
    path('fornecedores/', fornecedores, name='fornecedores'),
    path('produtos-list/', produtos, name='produtos'),
    path('representantes/', representante, name='representantes'),
    path('fornecedor/', fornecedor, name='fornecedor'),
    path('representante/', representantes, name='representante'),
    path('<uuid:pk>/atualizar/', UpadteProdutoView.as_view(), name='atualizar-produto'),
    path('<uuid:pk>/delete/', DeleteProdutoView.as_view(), name='delete-produto'),
    path('<int:pk>/atualizar/', UpadteRepresentanteView.as_view(), name='atualizar-representante'),
    path('<int:pk>/delete/', DeleteRepresentanteView.as_view(), name='excluir-representante'),
    path('<int:pk>/editar/', UpadteFornecedorView.as_view(), name='editar-fornecedor'),
    path('<int:pk>/apagar/', DeleteFornecedorView.as_view(), name='apagar-fornecedor'),


]

pyzza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Sistema PYzza!'
admin.site.site_title = 'PYzza!'
admin.site.index_title = 'Sistema de Gerenciamento PYzza!'

core/models.py
from django.db import models
import uuid


class Base(models.Model):
    criacao = models.DateTimeField(auto_now_add=True)
    atualizacao = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Fornecedor(Base):
    empresa = models.CharField('Nome da Empresa', max_length=100)
    cnpj = models.CharField('CNPJ', max_length=18)
    telefone = models.CharField('Telefone', max_length=12, help_text='Digite o numero do Telefone')
    email = models.EmailField('E-mail', max_length=100, help_text='Digite seu email')

    class Meta:
        verbose_name_plural = 'Fornecedores'
        unique_together = ('empresa', 'cnpj', 'telefone', 'email',)

    def __str__(self):
        return self.empresa


class Produto(Base):
    id = models.UUIDField(default=uuid.uuid4(), primary_key=True, editable=False)
    nome = models.CharField('Nome do Produto', max_length=100, help_text='nome do produto')
    categoria = models.CharField('Categoria', max_length=200, help_text='Ex: frios, massas')
    preco = models.DecimalField('Preço', max_digits=8, decimal_places=2, help_text='R$')
    medida = models.CharField('Medida', max_length=2, help_text='Ex: kg, Un')
    estoque = models.IntegerField('Estoque Atual', null=True, blank=True, default=None)
    empresa = models.ForeignKey(Fornecedor, on_delete=models.CASCADE, null=True, blank=True, default=None)

    def __str__(self):
        return str(self.empresa)

    @property
    def situacao_produto(self):
        if self.estoque > 0 and self.estoque <= 20:
            return "Situação/Ruim"
        elif self.estoque > 20 and self.estoque <= 40:
            return 'Situação/Regular'
        elif self.estoque > 40 and self.estoque <= 50:
            return 'Situação/Bom'
        elif self.estoque > 50:
            return 'Situação/Excelente'

    @property
    def validade_produto(self):
        if self.nome > 'queijo':
            return 'Produto vencido'
        else:
            f'Produto a Vencer na data: {self.nome}'


class RepresentanteComercial(Base):
    empresa = models.OneToOneField(Fornecedor, on_delete=models.CASCADE)
    nomecontato = models.CharField('Nome do Representante', max_length=100)
    endereco = models.CharField('Endereço', max_length=100)
    bairro = models.CharField('Bairro', max_length=100)
    cep = models.CharField('CEP', max_length=10)
    cidade = models.CharField('Cidade', max_length=20)
    estado = models.CharField('Estado', max_length=2)
    cpf = models.CharField('CPF', max_length=20)

    class Meta:
        verbose_name_plural = 'Representantes Comerciais'
        unique_together = ('nomecontato', 'endereco', 'cpf',)

    def __str__(self):
        return self.nomecontato

core/forms.py
from django import forms
from .models import Produto, Fornecedor, RepresentanteComercial


class ProdutoModelForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'


class RepresentanteComercialModelForm(forms.ModelForm):
    class Meta:
        model = RepresentanteComercial
        fields = '__all__'


class FornecedorModelForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = '__all__'

core/views.py
from django.shortcuts import render
from .forms import ProdutoModelForm, FornecedorModelForm, RepresentanteComercialModelForm
from django.contrib import messages
from .models import Produto, Fornecedor, RepresentanteComercial
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'


class UpadteProdutoView(UpdateView):
    model = Produto
    template_name = 'produto_atualizar.html'
    fields = ['nome','preco', 'estoque']
    success_url = reverse_lazy('core:produtos')


class DeleteProdutoView(DeleteView):
    model = Produto
    template_name = 'produto_del.html'
    success_url = reverse_lazy('core:produtos')


class UpadteRepresentanteView(UpdateView):
    model = RepresentanteComercial
    template_name = 'representante_atualizar.html'
    fields = ['empresa', 'nomecontato', 'endereco', 'bairro', 'cep', 'cidade', 'estado', 'cpf']
    success_url = reverse_lazy('core:representantes')


class DeleteRepresentanteView(DeleteView):
    model = RepresentanteComercial
    template_name = 'representante_deletar.html'
    success_url = reverse_lazy('core:representantes')


class UpadteFornecedorView(UpdateView):
    model = Fornecedor
    template_name = 'fornecedor_atualizar.html'
    fields = ['empresa', 'cnpj', 'telefone', 'email']
    success_url = reverse_lazy('core:fornecedores')


class DeleteFornecedorView(DeleteView):
    model = Fornecedor
    template_name = 'fornecedor_deletar.html'
    success_url = reverse_lazy('core:fornecedores')


def produtos(request):

    context = {
        'produtos': Produto.objects.all()

    }
    return render(request, 'produtos.html', context)


def fornecedores(request):
    context = {
        'fornecedores': Fornecedor.objects.all()
    }
    return render(request, 'fornecedores.html', context)


def representante(request):
    context = {
        'representantes': RepresentanteComercial.objects.all()
    }
    return render(request, 'representantes.html', context)


def produto(request):
    if str(request.method) == 'POST':
        form = ProdutoModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            messages.success(request, 'Produto salvo com Sucesso.')
            form = ProdutoModelForm()
        else:
            messages.error(request, 'Erro ao salvar Produto.')
    else:
        form = ProdutoModelForm()
    context = {
        'form': form
    }
    return render(request, 'produto.html', context)


def fornecedor(request):
    if str(request.method) == 'POST':
        form = FornecedorModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            messages.success(request, 'Fornecedor salvo com Sucesso.')
            form = FornecedorModelForm()
        else:
            messages.error(request, 'Erro ao salvar Fornecedor.')
    else:
        form = FornecedorModelForm()
    context = {
        'form': form
    }
    return render(request, 'fornecedor.html', context)


def representantes(request):
    if str(request.method) == 'POST':
        form = RepresentanteComercialModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            messages.success(request, 'Representante salvo com Sucesso.')
            form = FornecedorModelForm()
        else:
            messages.error(request, 'Erro ao salvar Representante.')
    else:
        form = RepresentanteComercialModelForm()
    context = {
        'form': form
    }
    return render(request, 'representante.html', context)

core/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% if user.is_anonymous %}
        <title>Inicio</title>
    {% else %}
        <title>{% block title %}Sistema Pyzza{% endblock %}</title>
    {% endif %}
</head>
<body>
    <header>
        <nav class="navbar  navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'core:index' %}">Sistema Pyzza!</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
       <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

core/templates/fornecedor.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Fornecedor</title>
    {% bootstrap_css %}
</head>
<body>
        <div class="container">
                <img src="{% static 'images/home.png' %}" alt="100" width="200"/>
                <a class="btn btn-primary" href="{% url 'core:index' %}"><h8>voltar para a pagina inicial</h8></a>
                <a class="btn btn-primary" href="{% url 'core:fornecedores' %}"><h8>fornecedores registrados</h8></a>
                <h2 class="text-center">Cadastro de Fornecedores</h2>
                {% bootstrap_messages %}

                <form action="{% url 'core:fornecedor' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                {% endbuttons %}
                </form>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/fornecedor_atualizar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Editar Fornecedor</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-warning">
                <a href="{% url 'core:fornecedores' %}">Cancelar</a>
            </button>
    </form>
{% endblock %}

core/templates/fornecedor_deletar.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Tem certeza que deseja Deletar o fornecedor "{{ object }}</p>
            {% buttons %}
                <button type="submit" class="btn btn-primary">Confirmar</button>
                <button type="button" class="btn btn-warning">
                    <a href="{% url 'core:fornecedores' %}">Cancelar</a>
                </button>
            {% endbuttons %}
    </form>
{% endblock %}

core/templates/fornecedores.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Fornecedores</title>
    {% bootstrap_css %}
</head>
<body>
       <div class="container">
            <img src="{% static 'images/home.png' %}" alt="100" width="200"/>
            <a  class="btn btn-primary"  href="{% url 'core:produtos' %}"><h8>ir para produtos</h8></a>
            <a  class="btn btn-primary"  href="{% url 'core:representantes' %}"><h8>ir para representantes</h8></a>
            <a  class="btn btn-success"  href="{% url 'core:index' %}"><h8>voltar para pagina inicial</h8></a>
            {% if user.is_superuser %}
                <a  class="btn btn-secondary"  href="{% url 'core:fornecedor' %}"><h8>cadastrar novo fornecedor</h8></a>
            {% endif %}
            <h2 class="text-center">Fornecedores Cadastrados no Sistema PYzza!</h2>
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">Empresa</th>
                        <th scope="col" class="text-center">CNPJ</th>
                        <th scope="col" class="text-center">Telefone</th>
                        <th scope="col" class="text-center">Email</th>
                        {% if user.is_superuser %}
                            <th scope="col" class="text-center">Opção</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for cliente in fornecedores %}
                        <tr>
                            <td scope="row" class="text-center">{{ cliente.empresa }}</td>
                             <td scope="row" class="text-center">{{ cliente.cnpj }}</td>
                             <td scope="row" class="text-center">{{ cliente.telefone }}</td>
                             <td scope="row" class="text-center">{{ cliente.email }}</td>
                             <td scope="row">
                                {% if user.is_superuser %}
                                    <a class="btn btn-info" href="{% url 'core:editar-fornecedor' cliente.pk %}">Editar</a>
                                    <a class="btn btn-dark" href="{% url 'core:apagar-fornecedor' cliente.pk %}">Deletar</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class ="container text-center" role="alert">
        <img src="{% static 'images/home.png' %}" alt="100"  width="500"/>
        {% if user.is_anonymous %}
            <h3 class="alert alert-primary">Sistema de Informação para Pizzarias</h3>
        {% endif %}
        {% if user.is_anonymous %}
            <a class="#" href="{% url 'core:index' %}"></a>
        {% endif %}
            {% if user.is_superuser %}
            <div class="alert alert-primary text-center" role="alert">
                <h3>Bem Vindo ao Sistema de Informação para Pizzarias</h3>
                <a class="btn btn-success" href="{% url 'core:produto' %}">Cadastrar Produtos</a>
                <a class="btn btn-success" href="{% url 'core:fornecedor' %}">Cadastrar Fornecedores</a>
                <a class="btn btn-success" href="{% url 'core:representante' %}">Cadastrar Representante</a>
            {% endif %}
            </div>
        {% if user.is_authenticated %}
            <div class="alert alert-danger text-center" role="alert">

                    <h3>Registros do Sistema Pyzza!</h3>
                    <a class= "btn btn-danger" href="{% url 'core:produtos' %}">Produtos</a>
                    <a class="btn btn-danger" href="{% url 'core:fornecedores' %}">Fornecedores</a>
                    <a class="btn btn-danger" href="{% url 'core:representantes' %}">Representantes</a>
            </div>
                <div class="alert alert-secondary text-center">
                    <a>Cadastrar: Login na Aréa Administrativa
                    <a class="btn btn-dark" href="http://localhost:8000/admin/login/?next=/admin/">acessar</a></a>
                </div>
        {% endif %}

    </div>
{% endblock %}

core/templates/produto.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Produto</title>
    {% bootstrap_css %}
</head>
<body>
        <div class="container">
                <img src="{% static 'images/home.png' %}" alt="100" width="200"/>
                <a class="btn btn-primary" href="{% url 'core:index' %}"><h8>voltar para a pagina inicial</h8></a>
                <a class="btn btn-primary" href="{% url 'core:produtos' %}"><h8>produtos registrados</h8></a>
                <h2 class="text-center">Cadastro de Produtos</h2>
                {% bootstrap_messages %}

                <form action="{% url 'core:produto' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                {% endbuttons %}

                </form>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/produto_atualizar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h1>Produtos</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-warning">
                <a href="{% url 'core:produtos' %}">Cancelar</a>
            </button>
    </form>
{% endblock %}

core/templates/produto_del.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Tem certeza que deseja Deletar o produto "{{ object }}</p>
            {% buttons %}
                <button type="submit" class="btn btn-primary">Confirmar</button>
                <button type="button" class="btn btn-warning">
                    <a href="{% url 'core:produtos' %}">Cancelar</a>
                </button>
            {% endbuttons %}
    </form>
{% endblock %}

core/templates/produtos.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Produtos</title>
    {% bootstrap_css %}
</head>
<body>
        <div class="container">
            <img src="{% static 'images/home.png' %}" alt="100" width="200"/>
            <a  class="btn btn-danger"  href="{% url 'core:fornecedores' %}"><header>ir para fornecedores</header></a>
            <a  class="btn btn-danger"  href="{% url 'core:representantes' %}"><header>ir para representantes</header></a>
            <a  class="btn btn-warning"  href="{% url 'core:index' %}"><header>voltar para pagina inicial</header></a>
            {% if user.is_superuser %}
                <a  class="btn btn-secondary"  href="{% url 'core:produto' %}"><header>cadastrar novo produto</header></a>
            {% endif %}
            <h2 class="text-center">Produtos Cadastrados no Sistema PYzza!</h2>
            <table class="table table-danger">
                <thead>
                    <tr>
                        <th scope="col">Nome do Produto</th>
                        <th scope="col" class="text-center">Preço</th>
                        <th scope="col" class="text-center">Medida</th>
                        <th scope="col" class="text-center">Nome da Empresa</th>
                        <th scope="col" class="text-center">Estoque Atual</th>
                        <th scope="col">Situação/Estoque</th>
                        <th scope="col">Validade</th>
                        {% if user.is_superuser %}
                            <th scope="col" class="text-center">Opção</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for produto in produtos %}
                        <tr>
                            <td scope="row"><a href="#modal{{produto.id}}" data-toggle="modal">{{ produto.nome }}</a></td>
                            <td scope="row" class="text-center">{{ produto.preco }}</td>
                            <td scope="row" class="text-center">{{ produto.medida }}</td>
                            <td scope="row" class="text-center">{{ produto.empresa }}</td>
                            <td scope="row" class="text-center">{{ produto.estoque }}</td>
                            <td scope="row">{{ produto.situacao_produto}}</td>
                            <td scope="row">{{ produto.validade_produto}}</td>
                            <td scope="row">
                                {% if user.is_superuser %}
                                    <a class="btn btn-danger" href="{% url 'core:atualizar-produto' produto.pk %}">Editar</a>
                                    <a class="btn btn-primary" href="{% url 'core:delete-produto' produto.pk %}">Deletar</a>
                                {% endif %}
                            </td>
                        </tr>
                        <div class="modal fade bd-example-modal-lg show" id="modal{{produto.id}}" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">{{produto.nome}}</h5>
                                        <button type="button" class="close" data-dismiss="modal">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body" id="dynamic-content">
                                        <p>Registro de entrada em: {{produto.criacao}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </tbody>
            </table>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/representante.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Representante</title>
    {% bootstrap_css %}
</head>
<body>
        <div class="container">
               <img src="{% static 'images/home.png' %}" alt="100" width="200"/>
               <a class="btn btn-primary" href="{% url 'core:index' %}"><h8>voltar para a pagina inicial</h8></a>
               <a class="btn btn-primary" href="{% url 'core:representantes' %}"><h8>representantes registrados</h8></a>
               <h2 class="text-center">Cadastro de Representantes</h2>

                {% bootstrap_messages %}

                <form action="{% url 'core:representante' %}" method="post" class="form" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                {% endbuttons %}
                </form>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>

core/templates/representante_atualizar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Editar Representante</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Salvar</button>
            <button type="button" class="btn btn-warning">
                <a href="{% url 'core:representantes' %}">Cancelar</a>
            </button>
    </form>
{% endblock %}

core/templates/representante_deletar.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Tem certeza que deseja Deletar o representante "{{ object }}</p>
            {% buttons %}
                <button type="submit" class="btn btn-primary">Confirmar</button>
                <button type="button" class="btn btn-warning">
                    <a href="{% url 'core:representantes' %}">Cancelar</a>
                </button>
            {% endbuttons %}
    </form>
{% endblock %}

core/templates/representantes.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Representantes</title>
    {% bootstrap_css %}
</head>
<body>
       <div class="container-fluid">
            <img src="{% static 'images/home.png' %}" alt="100" width="200"/>
            <a  class="btn btn-success"  href="{% url 'core:produtos' %}"><h8>ir para produtos</h8></a>
            <a  class="btn btn-success"  href="{% url 'core:fornecedores' %}"><h8>ir para fornecedores</h8></a>
            <a  class="btn btn-primary"  href="{% url 'core:index' %}"><h8>voltar para pagina inicial</h8></a>
            {% if user.is_superuser %}
                <a  class="btn btn-secondary"  href="{% url 'core:representante' %}"><h8>cadastrar novo representante</h8></a>
            {% else %}
                <a href="{% url 'core:index' %}"></a>
            {% endif %}
            <h2 class="text-center">Representantes Cadastrados no Sistema PYzza!</h2>
            <table class="table table-success">
                <thead>
                    <tr>
                        <th scope="col">Empresa</th>
                        <th scope="col">Representante</th>
                        <th scope="col" class="text-center">Endereço</th>
                        <th scope="col">Bairro</th>
                        <th scope="col">CEP</th>
                        <th scope="col">Cidade</th>
                        <th scope="col" class="text-center">Estado</th>
                        <th scope="col" class="text-center">CPF</th>
                        {% if user.is_superuser %}
                            <th scope="col" class="text-center">Opção</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for c in representantes %}
                        <tr>
                            <td scope="row">{{ c.empresa }}</td>
                            <td scope="row">{{ c.nomecontato }}</td>
                            <td scope="row">{{ c.endereco }}</td>
                            <td scope="row">{{ c.bairro }}</td>
                            <td scope="row">{{ c.cep }}</td>
                            <td scope="row">{{ c.cidade }}</td>
                            <td scope="row" class="text-center">{{ c.estado }}</td>
                            <td scope="row">{{ c.cpf }}</td>
                            <td scope="row">
                                {% if user.is_superuser %}
                                    <a class="btn btn-danger" href="{% url 'core:atualizar-representante' c.pk %}">Editar</a>
                                    <a class="btn btn-secondary" href="{% url 'core:excluir-representante' c.pk %}">Deletar</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
</div>
{% bootstrap_javascript jquery='full' %}
</body>
</html>